name: "Retry Failed PR Checks"
description: "Retries failed PR checks"
inputs:
  max-retries:
    description: "Maximum number of retries"
    required: true
    default: "3"
  repository:
    description: "Repository to retry checks for"
    required: true
  owner:
    description: "Owner of the repository"
    required: true
  token:
    description: "GitHub token"
    required: true
outputs:
  rerunJobs:
    description: "The jobs that were rerun"
  rerunJobsCount:
    description: "The number of jobs that were rerun"

runs:
  using: "node16"
  main: "dist/index.js"
